### ISSUE TITLE
ArgumentError when given <script> string

### ISSUE THREAD

**Issue by somlor** [philss/floki#136]
Trying to upgrade from `0.12.0` to `0.18.0` but getting an argument error when `Floki.text` receives a script tag:
```
Floki.text "<script>wat</script>"
** (ArgumentError) argument error
    :erlang.hd([])
    (floki) lib/floki/filter_out.ex:33: Floki.FilterOut.filter_out/2
    (floki) lib/floki.ex:285: Floki.text/2
```

**Comment by somlor** [comment]
@philss works great, thanks! 👍
