### ISSUE TITLE
html5ever faliled to compile

### ISSUE THREAD

**Issue by lpvm** [philss/floki#196]
I've installed rust, rust standard library, toolchain and cargo from the distro package manager.
Configured `mix.exs` as explained.
When trying `mix deps.compile`, I get the following error:
```
$ mix deps.compile
==> html5ever
Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
    Blocking waiting for file lock on build directory
   Compiling erlang_nif-sys v0.6.3
   Compiling phf_generator v0.7.21
   Compiling phf v0.7.21
   Compiling syn v0.11.11
   Compiling tendril v0.2.4
   Compiling string_cache_codegen v0.4.0
   Compiling phf_codegen v0.7.21
error: failed to run custom build command for `erlang_nif-sys v0.6.3`                                                    
process didn't exit successfully: `/home/lupe/prog/elixir/dre_scrappe/dre/_build/dev/rustler_crates/html5ever_nif/release/build/erlang_nif-sys-7f370c1b925fd94c/build-script-build` (exit code: 101)                                               
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.                                                  

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /home/lupe/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.3/build.rs:28:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
could not compile dependency :html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile html5ever", update it with "mix deps.update html5ever" or clean it with "mix deps.clean html5ever"                         
** (RuntimeError) Rust NIF compile error (rustc exit code 101)                                                           
    lib/mix/tasks/compile.rustler.ex:60: Mix.Tasks.Compile.Rustler.compile_crate/1                                       
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2                                                            
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1                                                 
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2                                          
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4                                            
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1                                 
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1    
```
The file `Cargo.toml` is as:
```cat deps/html5ever/native/html5ever_nif/Cargo.toml
[package]
name = "html5ever_nif"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]

[lib]
name = "html5ever_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "^0.17"
rustler_codegen = "^0.17"
#rustler = { path = "../../../Rustler/" }
#rustler_codegen = { path = "../../../Rustler/rustler_codegen/" }                                                        

html5ever = "0.16"
markup5ever = "0.1"

tendril = "0.2"
lazy_static = "0.2"
scoped-pool = "1"
```
The versions of Elixir and Erlang are:
```$ elixir -v
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]                                      

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```

Didn't find any help about this error in my web search.
What can I do?

**Comment by mischov** [comment]
Related: https://github.com/hansihe/html5ever_elixir/issues/11

**Comment by lpvm** [comment]
Thank you @mischov!
